### ISSUE TITLE
remove secret from github actions

### ISSUE THREAD

**Issue by janwinkler1** [hackathon-empty-string-team/empty-string#1]
- currently there is a secret key in the github action yml
- I think we should remove it to avoid exploitation
- then, invalidate the secret and create a new secret and add it to the repo secrets
- reference the secret with sometihng like in the actions yml: 
```
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://wwebec:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/wwebec/empty-string main
```

- wheter we want to delete the old token from the commit history we can discuss
